### ISSUE TITLE
Visual representation of the relation between IP and SAN

### ISSUE THREAD

**Issue by righettod** [righettod/tls-cert-discovery#1]
1. Generate a _network graph_ in order to show the relation between an IP and the SAN pointing to it.
2. Integrate this graph in the Excel result file as a new worksheet

**Comment by Mincka** [comment]
Mixed host-based graph with linked domains.

- Domains hosted on the same host are siblings
- Additional hosts found via the main host certificates are children

![image](https://user-images.githubusercontent.com/6184289/30780786-6a8fbcec-a113-11e7-9e3a-456a54b73fbd.png)

**Comment by righettod** [comment]
Python API found:
* https://networkx.github.io/documentation/stable/install.html

**Comment by righettod** [comment]
Done
